### ISSUE TITLE
Suggestion: Change fingering numbers

### ISSUE THREAD

**Issue by jsgarden** [morinted/art_of_chording#114]
As a pianist, I would love it if Plover's leading textbook, The Art of Chording, used the inside-to-outside fingering convention used on the piano, with 1 corresponding to the thumb, and 5 corresponding to the pinky.
([Top Row](https://www.artofchording.com/layout/top-row.html), [Bottom Row](https://www.artofchording.com/layout/bottom-row.html))

Is there a finger numbering convention used in steno that is the opposite of piano playing, or was the current convention chosen arbitrarily a number of years ago and was never changed?

I'd love to contribute and submit a proper pull request, but I have seldom used git and/or GitHub.

Thank you!

**Comment by jan-Kulpas** [comment]
I dunno! I feel like the current convention is easier to understand for non piano players. I don't personally see a reason to change it as the convention is quickly dropped in favor of referring to key's directly.

**Comment by morinted** [comment]
I think it's a neat idea that could be turned into a python dictionary!

**Comment by storeilly** [comment]
> As a pianist, I would love it if Plover's leading textbook, The Art of Chording, used the inside-to-outside fingering convention used on the piano, with 1 corresponding to the thumb, and 5 corresponding to the pinky. ([Top Row](https://www.artofchording.com/layout/top-row.html), [Bottom Row](https://www.artofchording.com/layout/bottom-row.html))
> 
> Is there a finger numbering convention used in steno that is the opposite of piano playing, or was the current convention chosen arbitrarily a number of years ago and was never changed?
> 
> I'd love to contribute and submit a proper pull request, but I have seldom used git and/or GitHub.
> 
> Thank you!

I think it would be a great idea to reverse the finger numbering to match musicians. I've played the piano for over 50 years and am just beginning to learn steno. I think it would be easier for me to relate to the numbering system I'm familiar with  (and probably many other musicians) to get started. I'm happy create a pull request when I get a bit of time if it helps.
