### ISSUE TITLE
There is no capitalize and return briefs in the Top Row > brief page

### ISSUE THREAD

**Issue by drogga3** [morinted/art_of_chording#24]
https://www.artofchording.com/layout/top-row.html#how-to-practice
The lesson told us to stroke -T PUP SAT TP-PL, which outputs "the pup sat.", however the page expects the output "The pup sat.", this is because capitalize brief were never introduced.

Also it's useful to introduce New Line briefs for this page: https://www.artofchording.com/layout/top-row.html#practice
so the output is seperated into new lines.

Lastly, what's -T PAL H H T TP-PL supposed to output? (Number 4, Lesson 1: Translate.)

**Comment by morinted** [comment]
Translation is "the pal had had it."

Closing with a note added to lesson to not worry about capitalization and spelling yet.
