### ISSUE TITLE
Hardware?

### ISSUE THREAD

**Issue by neopaf** [morinted/art_of_chording#74]
Please add a hint as to where one can get some inexpensive hardware?

**Comment by MarcelloTheArcane** [comment]
There's a link through to the Open Steno Project, which has a hardware page: https://github.com/openstenoproject/plover/wiki/Supported-Hardware#dedicated-machines-designed-for-use-with-plover

**Comment by neopaf** [comment]
Right! There is. Just missed it. 
Thanks!
